config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => redirect('/boxes')

  resources :boxes

  # view routes
  get '/widgets' => 'widgets#index'

  get 'dashboard/dashboard_v1'
  get '/api/i18n/:locale' => 'api#i18n'

  # the rest goes to root
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
require 'rqrcode'

class Box < ApplicationRecord
  include Rails.application.routes.url_helpers
  has_attached_file :qr

  validates_uniqueness_of :title
  validates_attachment_content_type :qr, :content_type => /\Aimage\/.*\Z/

  after_commit :generate_qr, unless: :has_qr?

  private
  def generate_qr
    path = Rails.root.join("tmp", "#{SecureRandom.uuid}.png")
    qr_text = Rails.application.routes.url_helpers.box_url(self, host: ENV['ROOT_URL'])
    qrcode = RQRCode::QRCode.new(qr_text)
    png = qrcode.as_png(file: path, size: 350, border_modules: 0)
    update_qr(path)
  end

  def update_qr(path)
    self.qr = File.open(path)
    self.save!
    remove_file(path)
  end

  def remove_file(path)
    File.delete(path)
  end

  def has_qr?
    !self.qr.url.match?("missing")
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  
  def documentation
    render file: "app/assets/documentation/readme.md"
  end

  def datatable
    render file: "app/assets/api/datatable.json"
  end

  def jqgrid
    render file: "app/assets/api/jqgrid.json"
  end

  def jqgridtree
    render file: "app/assets/api/jqgrid-tree.json"
  end

  def i18n
    # locale param was defined in config/routes.rb
    render file: "app/assets/i18n/" + params['locale']
  end

  def xeditablegroups
    render file: "app/assets/api/xeditable-groups.json"
  end

  def xeditable
    render :nothing => true
  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def blog
  end

  def blog_article_view
  end

  def blog_articles
  end

  def blog_post
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  def new
    @box = Box.new
  end

  def create
    @box = Box.new(box_params)
    if @box.save
      redirect_to @box
    else
      flash.now[:error] = @box.errors.full_messages
      render action: "new"
    end
  end

  def update
    @box = Box.find(params[:id])
    @box.update_attributes(processed: params[:processed])
    redirect_to @box
  end

  def edit
  end

  def destroy
  end

  def index
    @boxes = Box.all
  end

  def show
    @box = Box.find(params[:id])
  end

  private
  def box_params
    params.require(:box).permit(:title, :content)
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def flot
  end

  def radial
  end

  def chartjs
  end

  def chartist
  end

  def morris
  end

  def rickshaw
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def standard
  end

  def extended
  end

  def validation
  end

  def upload
  end

  def wizard
  end

  def xeditable
  end

  def imgcrop
  end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def forum_categories
  end

  def forum_topics
  end

  def forum_discussion
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def google
  end

  def vector
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'pages'

  def login
  end

  def register
  end

  def recover
  end

  def lock
  end

  # set another layout for a specific action
  def template
    render :layout => 'application'
  end

  def notfound
  end

  def error500
  end

  def maintenance
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/documentation_helper.rb
module DocumentationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/multilevel_helper.rb
module MultilevelHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/boxes/create.html.erb
<h1>Boxes#create</h1>
<p>Find me in app/views/boxes/create.html.erb</p>

app/views/boxes/destroy.html.erb
<h1>Boxes#destroy</h1>
<p>Find me in app/views/boxes/destroy.html.erb</p>

app/views/boxes/edit.html.erb
<h1>Boxes#edit</h1>
<p>Find me in app/views/boxes/edit.html.erb</p>

app/views/boxes/index.html.erb
<h3>Cajas
   <small>Inventario de cajas</small>
</h3>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
       <div class="panel panel-default">
          <div class="panel-heading">
             Cajas
          </div>
          <div class="panel-body">
             <table id="boxes" class="table table-striped table-hover">
                <thead>
                   <tr>
                      <th>Id</th>
                      <th>Title</th>
                      <th>Processed</th>
                   </tr>
                </thead>
                <tbody>
                  <% @boxes.each do |box| %>
                    <tr class="gradeA">
                      <td><%= link_to box.id, box %> </td>
                      <td><%= box.title %> </td>
                      <td><%= box.processed %> </td>
                    </tr>
                  <% end %>
                </tbody>
             </table>
          </div>
       </div>
       <%= link_to "New Box", new_box_path, class: "btn btn-info"  %>
    </div>
  </div>
</div>

app/views/boxes/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">NEW BOX</div>
      <div class="panel-body">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg.first, class: "alert alert-info" %>
        <% end %>

         <%= form_for @box do |f| %>
           <fieldset>
              <div class="form-group">
                  <%= f.label("input-id-1", "Title", class: "col-sm-2 control-label") %>
                <div class="col-sm-10">
                  <%= f.text_field :title, class: "form-control" %>
                </div>
              </div>
           </fieldset>
           <fieldset>
              <div class="form-group">
                 <label for="input-id-1" class="col-sm-2 control-label">Content</label>
               <div class="col-sm-10">
                  <div data-role="editor-toolbar" data-target="#editor" class="btn-toolbar btn-editor">
                     <div class="btn-group dropdown">
                        <a data-toggle="dropdown" title="Font" class="btn btn-default">
                           <em class="fa fa-font"></em><b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                           <li><a href="" data-edit="fontName Arial" style="font-family:'Arial'">Arial</a>
                           </li>
                           <li><a href="" data-edit="fontName Sans" style="font-family:'Sans'">Sans</a>
                           </li>
                           <li><a href="" data-edit="fontName Serif" style="font-family:'Serif'">Serif</a>
                           </li>
                        </ul>
                     </div>
                     <div class="btn-group dropdown">
                        <a data-toggle="dropdown" title="Font Size" class="btn btn-default">
                           <em class="fa fa-text-height"></em>&nbsp;<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                           <li><a href="" data-edit="fontSize 5" style="font-size:24px">Huge</a>
                           </li>
                           <li><a href="" data-edit="fontSize 3" style="font-size:18px">Normal</a>
                           </li>
                           <li><a href="" data-edit="fontSize 1" style="font-size:14px">Small</a>
                           </li>
                        </ul>
                     </div>
                     <div class="btn-group">
                        <a data-edit="bold" data-toggle="tooltip" title="Bold (Ctrl/Cmd+B)" class="btn btn-default">
                           <em class="fa fa-bold"></em>
                        </a>
                        <a data-edit="italic" data-toggle="tooltip" title="Italic (Ctrl/Cmd+I)" class="btn btn-default">
                           <em class="fa fa-italic"></em>
                        </a>
                        <a data-edit="strikethrough" data-toggle="tooltip" title="Strikethrough" class="btn btn-default">
                           <em class="fa fa-strikethrough"></em>
                        </a>
                        <a data-edit="underline" data-toggle="tooltip" title="Underline (Ctrl/Cmd+U)" class="btn btn-default">
                           <em class="fa fa-underline"></em>
                        </a>
                     </div>
                     <div class="btn-group">
                        <a data-edit="insertunorderedlist" data-toggle="tooltip" title="Bullet list" class="btn btn-default">
                           <em class="fa fa-list-ul"></em>
                        </a>
                        <a data-edit="insertorderedlist" data-toggle="tooltip" title="Number list" class="btn btn-default">
                           <em class="fa fa-list-ol"></em>
                        </a>
                        <a data-edit="outdent" data-toggle="tooltip" title="Reduce indent (Shift+Tab)" class="btn btn-default">
                           <em class="fa fa-dedent"></em>
                        </a>
                        <a data-edit="indent" data-toggle="tooltip" title="Indent (Tab)" class="btn btn-default">
                           <em class="fa fa-indent"></em>
                        </a>
                     </div>
                     <div class="btn-group">
                        <a data-edit="justifyleft" data-toggle="tooltip" title="Align Left (Ctrl/Cmd+L)" class="btn btn-default">
                           <em class="fa fa-align-left"></em>
                        </a>
                        <a data-edit="justifycenter" data-toggle="tooltip" title="Center (Ctrl/Cmd+E)" class="btn btn-default">
                           <em class="fa fa-align-center"></em>
                        </a>
                        <a data-edit="justifyright" data-toggle="tooltip" title="Align Right (Ctrl/Cmd+R)" class="btn btn-default">
                           <em class="fa fa-align-right"></em>
                        </a>
                        <a data-edit="justifyfull" data-toggle="tooltip" title="Justify (Ctrl/Cmd+J)" class="btn btn-default">
                           <em class="fa fa-align-justify"></em>
                        </a>
                     </div>
                     <div class="btn-group dropdown">
                        <a data-toggle="dropdown" title="Hyperlink" class="btn btn-default">
                           <em class="fa fa-link"></em>
                        </a>
                        <div class="dropdown-menu">
                           <div class="input-group ml-xs mr-xs">
                              <input id="LinkInput" placeholder="URL" type="text" data-edit="createLink" class="form-control input-sm" />
                              <div class="input-group-btn">
                                 <button type="button" class="btn btn-sm btn-default">Add</button>
                              </div>
                           </div>
                        </div>
                        <a data-edit="unlink" data-toggle="tooltip" title="Remove Hyperlink" class="btn btn-default">
                           <em class="fa fa-cut"></em>
                        </a>
                     </div>
                     <div class="btn-group">
                        <a id="pictureBtn" data-toggle="tooltip" title="Insert picture (or just drag &amp; drop)" class="btn btn-default">
                           <em class="fa fa-picture-o"></em>
                        </a>
                        <input type="file" data-edit="insertImage" style="position:absolute; opacity:0; width:41px; height:34px" />
                     </div>
                     <div class="btn-group pull-right">
                        <a data-edit="undo" data-toggle="tooltip" title="Undo (Ctrl/Cmd+Z)" class="btn btn-default">
                           <em class="fa fa-undo"></em>
                        </a>
                        <a data-edit="redo" data-toggle="tooltip" title="Redo (Ctrl/Cmd+Y)" class="btn btn-default">
                           <em class="fa fa-repeat"></em>
                        </a>
                     </div>
                  </div>
                  <div style="overflow:scroll; height:250px;max-height:250px" id="content" class="form-control wysiwyg mt-lg">Type something ...</div>
                  <%= f.hidden_field "content" %>
               </div>
              </div>
           </fieldset>
           <input type="button" onclick="myFunction()" class="mb-sm btn btn-primary" role="button" value="Create">
          <% end %>
      </div>
    </div>
    <a href="/" >List of boxes</a>
  </div>
</div>

<script>
function myFunction() {
  $("#box_content").val($('#content').html());
  $("#new_box").submit();
}
</script>

app/views/boxes/show.html.erb
<h3><%= "#{@box.id} - #{@box.title}" %></h3>
<div class="row">
  <div class="col-lg-4">
    <div class="panel panel-default">
       <div class="panel-body">
          <div class="text-info">QR Code</div>
          <div class="text-center pv-xl">
            <img src=<%= image_path @box.qr.url %> alt=""  />
          </div>
       </div>
       <div class="panel-footer">
          <p class="text-muted">
             <em class="fa fa-upload fa-fw"></em>
             <span><%= @box.title %></span>
          </p>
       </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="panel b">
       <table class="table bb">
          <tbody>
             <tr>
                <td>
                   <strong>Title</strong>
                </td>
                <td><%= @box.title %></td>
             </tr>
             <tr>
                <td>
                   <strong>Content</strong>
                </td>
                <td><%= @box.content.html_safe %></td>
             </tr>
             <tr>
                <td>
                   <strong>Processed?</strong>
                </td>
                <td><%= @box.processed %></td>
             </tr>
             <tr>
                <td>
                   <strong>Created at</strong>
                </td>
                <td><%= @box.created_at %></td>
             </tr>
             <tr>
                <td>
                </td>
                <td>
                  <%= form_tag box_path(@box, processed: true), method: :put do %>
                    <%= hidden_field_tag :box_id, @box.id %>
                    <%= submit_tag 'Process!', class: "mb-sm btn btn-sm btn-danger" -%>
                  <% end %>
                </td>
             </tr>
          </tbody>
       </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <a href="/" class="mb-sm btn btn-primary" role="button">List of boxes</a>
  </div>
</div>

app/views/boxes/update.html.erb
<h1>Boxes#update</h1>
<p>Find me in app/views/boxes/update.html.erb</p>